name: Publish release to PyPI

on:
  release:
    types:
    - created

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false
    - name: Build package
      run: uv build
        # Check that basic features work and we didn't miss to include crucial files
        # - name: Smoke test (wheel)
        #   run: uv run --isolated --no-project -p 3.13 --with dist/*.whl tests/smoke_test.py
        # - name: Smoke test (source distribution)
        #   run: uv run --isolated --no-project -p 3.13 --with dist/*.tar.gz tests/smoke_test.py
    - run: uv publish --trusted-publishing always
